/**
 * Domain types for Encountive Content Studio.
 *
 * These mirror the data model in
 * docs/encountive-content-studio-build-spec.md (section 4). They are hand-written
 * for now so the UI can be typed before the database exists. Once the Supabase
 * schema is created, generate `database.types.ts` from it
 * (`supabase gen types typescript`) and derive these from that source of truth.
 *
 * Every table carries `org_id` (directly or via a parent) and is protected by
 * Row Level Security — multi-tenant from day one.
 */

export type UUID = string;

/** Lifecycle of an uploaded/generated image asset. */
export type AssetStatus = "uploaded" | "analyzing" | "ready";

/** Where an asset came from. */
export type AssetSource = "uploaded" | "generated";

/** Lifecycle of a carousel content request. */
export type ContentRequestStatus =
  | "queued"
  | "generating"
  | "in_review"
  | "approved";

/** Links a Supabase Auth user to an organization. */
export interface Profile {
  id: UUID; // references auth.users
  org_id: UUID;
  role: string; // e.g. "owner", "editor"
  full_name: string | null;
  created_at: string;
}

export interface Organization {
  id: UUID;
  name: string;
  created_at: string;
}

export interface BrandKit {
  id: UUID;
  org_id: UUID;
  name: string;
  colors: Record<string, unknown>; // jsonb
  fonts: Record<string, unknown>; // jsonb
  logo_url: string | null;
  voice_guidelines: string | null;
  created_at: string;
}

/** The image library — uploaded and generated images live here together. */
export interface Asset {
  id: UUID;
  org_id: UUID;
  storage_path: string; // path in the `assets` storage bucket
  title: string | null; // auto-generated by the vision model; editable
  description: string | null; // auto-generated; basis for the embedding
  tags: string[];
  source: AssetSource;
  status: AssetStatus;
  mime_type: string | null;
  width: number | null;
  height: number | null;
  embedding: number[] | null; // vector(N); N matches the embedding model
  created_at: string;
}

export interface Project {
  id: UUID;
  org_id: UUID;
  name: string;
  status: string;
  created_at: string;
}

/** Join table — this IS the project board. */
export interface ProjectAsset {
  project_id: UUID;
  asset_id: UUID;
  position: number; // display order on the board
  created_at: string;
}

/** One carousel job. */
export interface ContentRequest {
  id: UUID;
  project_id: UUID;
  brand_kit_id: UUID;
  topic: string | null;
  brief: string | null;
  target_platform: string | null;
  status: ContentRequestStatus;
  created_at: string;
}

export interface Carousel {
  id: UUID;
  request_id: UUID;
  status: string;
  slide_count: number;
  output_path: string | null; // finished carousel in the `renders` bucket
  created_at: string;
}

export interface Slide {
  id: UUID;
  carousel_id: UUID;
  position: number;
  headline: string | null;
  body_copy: string | null;
  asset_id: UUID | null; // the image this slide uses (reused or generated)
  render_path: string | null; // the finished slide image
  created_at: string;
}
