/**
 * Domain types for Encountive Content Studio.
 *
 * These mirror the data model in
 * docs/encountive-content-studio-build-spec.md (section 4). They are hand-written
 * for now so the UI can be typed before the database exists. Once the Supabase
 * schema is created, generate `database.types.ts` from it
 * (`supabase gen types typescript`) and derive these from that source of truth.
 *
 * Every table carries `org_id` (directly or via a parent) and is protected by
 * Row Level Security — multi-tenant from day one.
 */

export type UUID = string;

/** Lifecycle of an uploaded/generated image asset. */
export type AssetStatus = "uploaded" | "analyzing" | "ready";

/** Where an asset came from. */
export type AssetSource = "uploaded" | "generated";

/** Lifecycle of a carousel content request. */
export type ContentRequestStatus =
  | "queued"
  | "generating"
  | "in_review"
  | "approved";

/** Links a Supabase Auth user to an organization. */
export interface Profile {
  id: UUID; // references auth.users
  org_id: UUID;
  role: string; // e.g. "owner", "editor"
  full_name: string | null;
  created_at: string;
}

export interface Organization {
  id: UUID;
  name: string;
  created_at: string;
}

export interface BrandKit {
  id: UUID;
  org_id: UUID;
  name: string;
  colors: Record<string, unknown>; // jsonb
  fonts: Record<string, unknown>; // jsonb
  logo_url: string | null;
  voice_guidelines: string | null;
  created_at: string;
}

/** The image library — uploaded and generated images live here together. */
export interface Asset {
  id: UUID;
  org_id: UUID;
  storage_path: string; // path in the `assets` storage bucket
  title: string | null; // auto-generated by the vision model; editable
  description: string | null; // auto-generated; basis for the embedding
  tags: string[];
  source: AssetSource;
  status: AssetStatus;
  mime_type: string | null;
  width: number | null;
  height: number | null;
  embedding: number[] | null; // vector(N); N matches the embedding model
  created_at: string;
}

/** The music library — uploaded audio tracks, mirroring the image library. */
export interface AudioAsset {
  id: UUID;
  org_id: UUID;
  storage_path: string; // path in the `audio` storage bucket
  title: string | null; // defaults to the file name; editable
  artist: string | null;
  tags: string[];
  source: AssetSource;
  status: AssetStatus;
  mime_type: string | null;
  duration_seconds: number | null; // read in the browser at upload time
  created_at: string;
}

export interface Project {
  id: UUID;
  org_id: UUID;
  name: string;
  status: string;
  created_at: string;
}

/** Join table — this IS the project board. */
export interface ProjectAsset {
  project_id: UUID;
  asset_id: UUID;
  position: number; // display order on the board
  created_at: string;
}

/** One carousel job. */
export interface ContentRequest {
  id: UUID;
  project_id: UUID;
  brand_kit_id: UUID;
  topic: string | null;
  brief: string | null;
  target_platform: string | null;
  status: ContentRequestStatus;
  created_at: string;
}

export interface Carousel {
  id: UUID;
  request_id: UUID;
  status: string;
  slide_count: number;
  output_path: string | null; // finished carousel in the `renders` bucket
  audio_asset_id: UUID | null; // soundtrack for the video preview
  created_at: string;
}

/** One marketing video being assembled in the editor. */
export interface Video {
  id: UUID;
  org_id: UUID;
  project_id: UUID | null;
  title: string;
  status: "draft" | "rendering" | "ready" | "error";
  audio_asset_id: UUID | null; // soundtrack from the music library
  width: number; // output canvas, e.g. 1080x1350
  height: number;
  output_path: string | null; // finished MP4 in the `renders` bucket
  render_error: string | null;
  created_at: string;
}

/** One clip in a video — an image or a video-clip asset held on screen. */
export interface VideoClip {
  id: UUID;
  video_id: UUID;
  position: number;
  asset_id: UUID | null; // a still image from the image library…
  video_asset_id: UUID | null; // …or a clip from the video-clip library
  headline: string | null; // overlaid at the render layer, never baked in
  body_copy: string | null;
  duration_seconds: number;
  created_at: string;
}

/** The video-clip library — uploaded video files (b-roll, product clips). */
export interface VideoAsset {
  id: UUID;
  org_id: UUID;
  storage_path: string; // path in the `clips` storage bucket
  title: string | null;
  tags: string[];
  source: AssetSource;
  status: AssetStatus;
  mime_type: string | null;
  duration_seconds: number | null;
  width: number | null;
  height: number | null;
  created_at: string;
}

/** A connected social posting destination (page, IG account, LinkedIn…). */
export interface SocialConnection {
  id: UUID;
  org_id: UUID;
  provider: "facebook" | "instagram" | "linkedin";
  account_scope: "personal" | "company";
  display_name: string;
  external_id: string;
  access_token: string;
  token_expires_at: string | null;
  metadata: Record<string, unknown>; // provider extras (page token, IG id…)
  status: "connected" | "expired" | "error";
  created_at: string;
}

/** One publish attempt of a video or carousel to a social destination. */
export interface SocialPost {
  id: UUID;
  org_id: UUID;
  connection_id: UUID | null;
  video_id: UUID | null;
  request_id: UUID | null; // when sharing a carousel
  caption: string | null;
  status: "queued" | "posting" | "posted" | "failed";
  external_url: string | null;
  error: string | null;
  posted_at: string | null;
  created_at: string;
}

export interface Slide {
  id: UUID;
  carousel_id: UUID;
  position: number;
  headline: string | null;
  body_copy: string | null;
  asset_id: UUID | null; // the image this slide uses (reused or generated)
  render_path: string | null; // the finished slide image
  created_at: string;
}
