/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioRouteImport } from './routes/_studio'
import { Route as LoginRouteImport } from './routes/login'
import { Route as StudioIndexRouteImport } from './routes/_studio/index'
import { Route as StudioBrandRouteImport } from './routes/_studio/brand'
import { Route as StudioCampaignsRouteImport } from './routes/_studio/campaigns'
import { Route as StudioLibraryRouteImport } from './routes/_studio/library'
import { Route as StudioNewRouteImport } from './routes/_studio/new'
import { Route as StudioPublishRouteImport } from './routes/_studio/publish'
import { Route as StudioReviewRouteImport } from './routes/_studio/review'
import { Route as StudioCampaignsIndexRouteImport } from './routes/_studio/campaigns.index'
import { Route as StudioCampaignsIdRouteImport } from './routes/_studio/campaigns.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiOauthInstagramRouteImport } from './routes/api/oauth/instagram'
import { Route as ApiOauthLinkedinRouteImport } from './routes/api/oauth/linkedin'

const StudioRoute = StudioRouteImport.update({
  id: '/_studio',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioIndexRoute = StudioIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioRoute,
} as any)
const StudioBrandRoute = StudioBrandRouteImport.update({
  id: '/brand',
  path: '/brand',
  getParentRoute: () => StudioRoute,
} as any)
const StudioCampaignsRoute = StudioCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => StudioRoute,
} as any)
const StudioLibraryRoute = StudioLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => StudioRoute,
} as any)
const StudioNewRoute = StudioNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StudioRoute,
} as any)
const StudioPublishRoute = StudioPublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => StudioRoute,
} as any)
const StudioReviewRoute = StudioReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => StudioRoute,
} as any)
const StudioCampaignsIndexRoute = StudioCampaignsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudioCampaignsRoute,
} as any)
const StudioCampaignsIdRoute = StudioCampaignsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudioCampaignsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthInstagramRoute = ApiOauthInstagramRouteImport.update({
  id: '/api/oauth/instagram',
  path: '/api/oauth/instagram',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOauthLinkedinRoute = ApiOauthLinkedinRouteImport.update({
  id: '/api/oauth/linkedin',
  path: '/api/oauth/linkedin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof StudioIndexRoute
  '/login': typeof LoginRoute
  '/brand': typeof StudioBrandRoute
  '/campaigns': typeof StudioCampaignsRouteWithChildren
  '/library': typeof StudioLibraryRoute
  '/new': typeof StudioNewRoute
  '/publish': typeof StudioPublishRoute
  '/review': typeof StudioReviewRoute
  '/campaigns/$id': typeof StudioCampaignsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/oauth/instagram': typeof ApiOauthInstagramRoute
  '/api/oauth/linkedin': typeof ApiOauthLinkedinRoute
  '/campaigns/': typeof StudioCampaignsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/brand': typeof StudioBrandRoute
  '/library': typeof StudioLibraryRoute
  '/new': typeof StudioNewRoute
  '/publish': typeof StudioPublishRoute
  '/review': typeof StudioReviewRoute
  '/': typeof StudioIndexRoute
  '/campaigns/$id': typeof StudioCampaignsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/oauth/instagram': typeof ApiOauthInstagramRoute
  '/api/oauth/linkedin': typeof ApiOauthLinkedinRoute
  '/campaigns': typeof StudioCampaignsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_studio': typeof StudioRouteWithChildren
  '/login': typeof LoginRoute
  '/_studio/brand': typeof StudioBrandRoute
  '/_studio/campaigns': typeof StudioCampaignsRouteWithChildren
  '/_studio/library': typeof StudioLibraryRoute
  '/_studio/new': typeof StudioNewRoute
  '/_studio/publish': typeof StudioPublishRoute
  '/_studio/review': typeof StudioReviewRoute
  '/_studio/': typeof StudioIndexRoute
  '/_studio/campaigns/$id': typeof StudioCampaignsIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/oauth/instagram': typeof ApiOauthInstagramRoute
  '/api/oauth/linkedin': typeof ApiOauthLinkedinRoute
  '/_studio/campaigns/': typeof StudioCampaignsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/brand'
    | '/campaigns'
    | '/library'
    | '/new'
    | '/publish'
    | '/review'
    | '/campaigns/$id'
    | '/api/auth/$'
    | '/api/oauth/instagram'
    | '/api/oauth/linkedin'
    | '/campaigns/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/brand'
    | '/library'
    | '/new'
    | '/publish'
    | '/review'
    | '/'
    | '/campaigns/$id'
    | '/api/auth/$'
    | '/api/oauth/instagram'
    | '/api/oauth/linkedin'
    | '/campaigns'
  id:
    | '__root__'
    | '/_studio'
    | '/login'
    | '/_studio/brand'
    | '/_studio/campaigns'
    | '/_studio/library'
    | '/_studio/new'
    | '/_studio/publish'
    | '/_studio/review'
    | '/_studio/'
    | '/_studio/campaigns/$id'
    | '/api/auth/$'
    | '/api/oauth/instagram'
    | '/api/oauth/linkedin'
    | '/_studio/campaigns/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  StudioRoute: typeof StudioRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiOauthInstagramRoute: typeof ApiOauthInstagramRoute
  ApiOauthLinkedinRoute: typeof ApiOauthLinkedinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_studio': {
      id: '/_studio'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_studio/': {
      id: '/_studio/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof StudioIndexRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/brand': {
      id: '/_studio/brand'
      path: '/brand'
      fullPath: '/brand'
      preLoaderRoute: typeof StudioBrandRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/campaigns': {
      id: '/_studio/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof StudioCampaignsRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/library': {
      id: '/_studio/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof StudioLibraryRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/new': {
      id: '/_studio/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof StudioNewRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/publish': {
      id: '/_studio/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof StudioPublishRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/review': {
      id: '/_studio/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof StudioReviewRouteImport
      parentRoute: typeof StudioRoute
    }
    '/_studio/campaigns/': {
      id: '/_studio/campaigns/'
      path: '/'
      fullPath: '/campaigns/'
      preLoaderRoute: typeof StudioCampaignsIndexRouteImport
      parentRoute: typeof StudioCampaignsRoute
    }
    '/_studio/campaigns/$id': {
      id: '/_studio/campaigns/$id'
      path: '/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof StudioCampaignsIdRouteImport
      parentRoute: typeof StudioCampaignsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/instagram': {
      id: '/api/oauth/instagram'
      path: '/api/oauth/instagram'
      fullPath: '/api/oauth/instagram'
      preLoaderRoute: typeof ApiOauthInstagramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/oauth/linkedin': {
      id: '/api/oauth/linkedin'
      path: '/api/oauth/linkedin'
      fullPath: '/api/oauth/linkedin'
      preLoaderRoute: typeof ApiOauthLinkedinRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface StudioCampaignsRouteChildren {
  StudioCampaignsIdRoute: typeof StudioCampaignsIdRoute
  StudioCampaignsIndexRoute: typeof StudioCampaignsIndexRoute
}

const StudioCampaignsRouteChildren: StudioCampaignsRouteChildren = {
  StudioCampaignsIdRoute: StudioCampaignsIdRoute,
  StudioCampaignsIndexRoute: StudioCampaignsIndexRoute,
}

const StudioCampaignsRouteWithChildren = StudioCampaignsRoute._addFileChildren(
  StudioCampaignsRouteChildren,
)

interface StudioRouteChildren {
  StudioBrandRoute: typeof StudioBrandRoute
  StudioCampaignsRoute: typeof StudioCampaignsRouteWithChildren
  StudioLibraryRoute: typeof StudioLibraryRoute
  StudioNewRoute: typeof StudioNewRoute
  StudioPublishRoute: typeof StudioPublishRoute
  StudioReviewRoute: typeof StudioReviewRoute
  StudioIndexRoute: typeof StudioIndexRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioBrandRoute: StudioBrandRoute,
  StudioCampaignsRoute: StudioCampaignsRouteWithChildren,
  StudioLibraryRoute: StudioLibraryRoute,
  StudioNewRoute: StudioNewRoute,
  StudioPublishRoute: StudioPublishRoute,
  StudioReviewRoute: StudioReviewRoute,
  StudioIndexRoute: StudioIndexRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  StudioRoute: StudioRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiOauthInstagramRoute: ApiOauthInstagramRoute,
  ApiOauthLinkedinRoute: ApiOauthLinkedinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
