import type { Campaign, LibraryAsset } from "./types";

export const SEED_ASSETS: LibraryAsset[] = [
  {
    id: "ast-nurse",
    title: "Nurse, tablet, sim lab",
    kind: "still",
    url: "/stills/nurse-tablet.jpg",
    tags: ["cover", "nursing", "product", "portrait"],
    prompt: "Latina nurse in teal scrubs with tablet in a sunlit simulation lab",
  },
  {
    id: "ast-debrief",
    title: "Team debrief",
    kind: "still",
    url: "/stills/team-debrief.jpg",
    tags: ["coaching", "hospital", "team"],
    prompt: "Diverse clinical team in a debrief room",
  },
  {
    id: "ast-hands",
    title: "Skills lab hands",
    kind: "still",
    url: "/stills/skills-hands.jpg",
    tags: ["skills", "close", "training"],
    prompt: "Two pairs of hands practicing on a manikin arm",
  },
  {
    id: "ast-corridor",
    title: "Corridor conversation",
    kind: "still",
    url: "/stills/corridor-walk.jpg",
    tags: ["hospital", "workforce", "documentary"],
    prompt: "Nurse and physician walking a quiet modern corridor",
  },
  {
    id: "ast-students",
    title: "Nursing students",
    kind: "still",
    url: "/stills/students.jpg",
    tags: ["nursing", "programs", "students"],
    prompt: "Three nursing students at simulation-center workstations",
  },
  {
    id: "ast-educator",
    title: "Educator listening",
    kind: "still",
    url: "/stills/educator.jpg",
    tags: ["coaching", "portrait", "faculty"],
    prompt: "Clinical educator in profile during one-on-one coaching",
  },
  {
    id: "ast-tablet",
    title: "Over-shoulder tablet",
    kind: "still",
    url: "/stills/tablet-over.jpg",
    tags: ["product", "engine", "close"],
    prompt: "Over-shoulder tablet in a sim lab, abstract interface",
  },
  {
    id: "ast-wide",
    title: "Sim lab, wide",
    kind: "still",
    url: "/stills/sim-lab-wide.jpg",
    tags: ["lab", "wide", "video"],
    prompt: "Wide sunlit clinical simulation lab",
  },
  {
    id: "ast-story",
    title: "Story portrait",
    kind: "still",
    url: "/stills/story-portrait.jpg",
    tags: ["stories", "portrait", "vertical"],
    prompt: "Vertical portrait, nurse looking up from a tablet",
  },
  {
    id: "ast-desk",
    title: "Evidence desk",
    kind: "still",
    url: "/stills/evidence-desk.jpg",
    tags: ["evidence", "still-life"],
    prompt: "Navy desk still life, tablet and stethoscope",
  },
  {
    id: "ast-motion",
    title: "Nurse looks up",
    kind: "motion",
    url: "/motion/nurse-look.mp4",
    posterUrl: "/stills/nurse-tablet.jpg",
    tags: ["motion", "nursing", "hero"],
    prompt: "Slow push-in as the nurse looks toward camera",
  },
];

export const SEED_CAMPAIGNS: Campaign[] = [
  {
    id: "cmp-gap",
    title: "The AI readiness gap",
    brief:
      "Thought-leadership carousel for nursing-program deans. Use the Lancet numbers (90 / 79 / under 15). Name the gap, then Encountive as the practice layer. CTA: scoped 60–90 day pilot.",
    audience: "nursing-programs",
    channel: "linkedin",
    cta: "Start with a scoped pilot.",
    caption:
      "90% of health students see AI coming. Fewer than 15% feel ready to use it.\n\nExcitement is not proficiency. Encountive closes the gap the only way clinical teams trust: scenario → coaching → evidence, at scale.\n\nWe’re taking a handful of 60–90 day pilots with nursing programs this year.\n\n#ClinicalEducation #NursingSimulation #AIinHealthcare",
    status: "review",
    notes: "",
    createdAt: "2026-08-12T14:00:00.000Z",
    updatedAt: "2026-08-18T09:12:00.000Z",
    slides: [
      {
        id: "s-gap-1",
        layout: "cover",
        kicker: "The Lancet Regional Health",
        headline: "90% see AI coming. Under 15% feel ready.",
        body: "Excitement is not proficiency. Nursing programs need a practice layer.",
        visualPrompt: "Nurse with tablet in a sunlit simulation lab",
        imageUrl: "/stills/nurse-tablet.jpg",
      },
      {
        id: "s-gap-2",
        layout: "stat",
        kicker: "The gap",
        headline: "Ready to use it. Not ready to practice it.",
        body: "Students are excited. Faculty hours are finite. Simulation time is the bottleneck.",
        statValue: "79%",
        statLabel: "excited to use AI at work — Lancet",
        visualPrompt: "Nursing students at workstations",
        imageUrl: "/stills/students.jpg",
      },
      {
        id: "s-gap-3",
        layout: "photo",
        kicker: "What breaks",
        headline: "Feedback quality still depends on who is in the room.",
        body: "When the preceptor is stretched, coaching gets thin. Rubrics drift. Evidence stays anecdotal.",
        visualPrompt: "Educator listening during coaching",
        imageUrl: "/stills/educator.jpg",
      },
      {
        id: "s-gap-4",
        layout: "photo",
        kicker: "The Encountive Engine",
        headline: "Scenario. Coaching. Evidence.",
        body: "Every attempt is anchored to a rubric, followed by targeted remediation, and logged as exportable evidence.",
        visualPrompt: "Over-shoulder tablet in a sim lab",
        imageUrl: "/stills/tablet-over.jpg",
      },
      {
        id: "s-gap-5",
        layout: "quote",
        kicker: "Built differently",
        headline: "Scoring is transparent and auditable — never a black box.",
        body: "Adaptive remediation recognizes error patterns and serves the next best practice: a micro-lesson, a branched redo, or a harder case.",
        visualPrompt: "Skills-lab hands on a manikin arm",
        imageUrl: "/stills/skills-hands.jpg",
      },
      {
        id: "s-gap-6",
        layout: "close",
        kicker: "Nursing programs",
        headline: "Start with a scoped 60–90 day pilot.",
        body: "Baseline-to-post measurement. Conversion terms on success. A report you can take to QI and credentialing.",
        visualPrompt: "Team debrief in a bright room",
        imageUrl: "/stills/team-debrief.jpg",
      },
    ],
  },
  {
    id: "cmp-roi",
    title: "Hospital cohorts, modeled ROI",
    brief:
      "CNO / workforce carousel. Lead with 4.0x ROI, $150k turnover savings, 40% faculty prep reduction, 1.3 month payback. Serious, not salesy. CTA: scoped pilot.",
    audience: "hospital-systems",
    channel: "linkedin",
    cta: "Ask for the ROI breakdown.",
    caption:
      "Turnover is a seven-figure problem. Practice hours are the constraint.\n\nModeled for hospital cohorts: 4.0x ROI, up to $150k turnover savings, ~1.3 month payback, 40% less faculty prep.\n\nEncountive is the practice layer — rubric-first simulation with evidence you can defend.\n\n#WorkforceDevelopment #NurseRetention #ClinicalSimulation",
    status: "review",
    notes: "Check the $150k line with finance before anything public.",
    createdAt: "2026-08-14T11:20:00.000Z",
    updatedAt: "2026-08-19T16:40:00.000Z",
    slides: [
      {
        id: "s-roi-1",
        layout: "cover",
        kicker: "Hospital systems",
        headline: "4.0× projected ROI for hospital cohorts.",
        body: "A practice layer that pays back in weeks, not budget cycles.",
        visualPrompt: "Corridor conversation, nurse and physician",
        imageUrl: "/stills/corridor-walk.jpg",
      },
      {
        id: "s-roi-2",
        layout: "stat",
        kicker: "Turnover",
        headline: "The cost of losing one nurse is no longer abstract.",
        body: "Modeled annual savings from fewer exits — the number CNOs already feel.",
        statValue: "$150k",
        statLabel: "turnover cost savings / year, modeled",
        visualPrompt: "Clinical team debrief",
        imageUrl: "/stills/team-debrief.jpg",
      },
      {
        id: "s-roi-3",
        layout: "stat",
        kicker: "Faculty time",
        headline: "Prep time is the hidden tax on every cohort.",
        body: "Structured coaching and analytics so learners get consistent guidance — without another late night in the sim lab.",
        statValue: "40%",
        statLabel: "reduction in faculty prep time",
        visualPrompt: "Educator portrait",
        imageUrl: "/stills/educator.jpg",
      },
      {
        id: "s-roi-4",
        layout: "photo",
        kicker: "Payback",
        headline: "~1.3 months. Then the evidence keeps compounding.",
        body: "Attempt histories, heatmaps of common misses, time-to-competence — usable for QI and accreditation.",
        visualPrompt: "Tablet over-shoulder",
        imageUrl: "/stills/tablet-over.jpg",
      },
      {
        id: "s-roi-5",
        layout: "close",
        kicker: "Workforce development",
        headline: "See the full ROI breakdown. Then run a pilot.",
        body: "We’ll help you plan deployment, define metrics, and design scale — aligned to your review process.",
        visualPrompt: "Nurse with tablet",
        imageUrl: "/stills/nurse-tablet.jpg",
      },
    ],
  },
  {
    id: "cmp-nursing",
    title: "Nursing programs — the practice layer",
    brief:
      "Product carousel + a 6s motion cut for nursing programs. Mechanism over metaphor. Rubric-first, adaptive remediation, evidence at scale. Approved for LinkedIn.",
    audience: "nursing-programs",
    channel: "linkedin",
    cta: "Book a 30-minute working session.",
    caption:
      "Simulation that remembers what each learner missed — and assigns the next best practice.\n\nEncountive for nursing programs: rubric-first scenarios, adaptive coaching after every attempt, exportable evidence for accreditation.\n\nWeb and mobile now. XR in development, H1 2027.\n\n#NursingEducation #Simulation",
    status: "approved",
    notes: "",
    createdAt: "2026-08-08T09:00:00.000Z",
    updatedAt: "2026-08-17T13:05:00.000Z",
    motion: {
      id: "mot-nursing",
      prompt: "Slow push-in as the nurse looks toward camera, window light",
      sourceSlideId: "s-nurs-1",
      videoUrl: "/motion/nurse-look.mp4",
      originalUrl: "/motion/nurse-look.mp4",
      posterUrl: "/stills/nurse-tablet.jpg",
      status: "ready",
      duration: 6,
      aspectRatio: "1:1",
    },
    slides: [
      {
        id: "s-nurs-1",
        layout: "cover",
        kicker: "Nursing programs",
        headline: "The practice layer your faculty has been covering by hand.",
        body: "Repeatable encounters. Consistent coaching. Evidence you can defend.",
        visualPrompt: "Nurse with tablet in sim lab",
        imageUrl: "/stills/nurse-tablet.jpg",
      },
      {
        id: "s-nurs-2",
        layout: "photo",
        kicker: "Rubric-first",
        headline: "Every scenario is anchored to a competency you already teach.",
        body: "Scoring is transparent. Faculty stay in the loop. The engine does not invent standards.",
        visualPrompt: "Skills lab hands",
        imageUrl: "/stills/skills-hands.jpg",
      },
      {
        id: "s-nurs-3",
        layout: "photo",
        kicker: "Adaptive remediation",
        headline: "Miss a pattern once. Practice it next.",
        body: "A targeted micro-lesson, a branched redo, or a harder case — served after the attempt, not at the end of the term.",
        visualPrompt: "Students at workstations",
        imageUrl: "/stills/students.jpg",
      },
      {
        id: "s-nurs-4",
        layout: "photo",
        kicker: "Evidence at scale",
        headline: "From anecdotes to a cohort view.",
        body: "Completion, repeats, rubric deltas, heatmaps of common misses. QI-ready, not slide-deck folklore.",
        visualPrompt: "Team debrief",
        imageUrl: "/stills/team-debrief.jpg",
      },
      {
        id: "s-nurs-5",
        layout: "close",
        kicker: "Limited pilot spots",
        headline: "A 60–90 day run with a report you can take upstairs.",
        body: "Web and mobile now. XR in development for H1 2027.",
        visualPrompt: "Story portrait",
        imageUrl: "/stills/story-portrait.jpg",
      },
    ],
  },
];

const POOL = SEED_ASSETS.filter((a) => a.kind === "still");

export function pickStill(visualPrompt: string, index: number, used: Set<string>): string {
  const q = visualPrompt.toLowerCase();
  const scored = POOL.map((a) => {
    let s = 0;
    for (const t of a.tags) if (q.includes(t)) s += 2;
    if (a.prompt && q.split(" ").some((w) => a.prompt!.toLowerCase().includes(w))) s += 1;
    if (used.has(a.url)) s -= 5;
    return { a, s };
  }).sort((x, y) => y.s - x.s);
  const choice = scored[0]?.a ?? POOL[index % POOL.length]!;
  used.add(choice.url);
  return choice.url;
}
